version: '3.4'

services:
  mssql_db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@ssword1 -Q 'SELECT 1' || exit 1"]
        interval: 5s
        retries: 10
        start_period: 5s
        timeout: 3s
    restart: always
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: zsolt
      MINIO_ROOT_PASSWORD: P@ssword1
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}