name: .NET Core Desktop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: NoteShare.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build project
      run: |
        dotnet build
        if [ $? -eq 0 ]; then
          echo "Build succeeded."
        else
          echo "Build failed."
          exit 1  # Exit with non-zero code to indicate failure
        fi

    - name: Merge to Dev
      if: success() && startsWith(github.ref, 'refs/heads/features/')
      run: |
        git config --global user.name 'Kornél Hajtó'
        git config --global user.email 'kornelhajto2004@gmail.com'
        git checkout dev
        git merge ${{ github.ref }}
        git push origin dev
