name: .NET Core Desktop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: NoteShare.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Mono
      run: |
        sudo apt update
        sudo apt install mono-devel -y

    - name: Build and merge to Dev
      run: |
        dotnet build
        if [ $? -eq 0 ]; then
          git config --global user.name 'Kornél Hajtó'
          git config --global user.email 'kornelhajto2004@gmail.com'
          git checkout dev
          git merge ${{ github.ref }}
          git push origin dev
        else
          echo "Build failed, skipping merge to dev."
        fi
